In [2]:
import torch
x = torch.rand(5,3)
print(x)

tensor([[0.4726, 0.3390, 0.3574],
        [0.4065, 0.4583, 0.8193],
        [0.0911, 0.5342, 0.8484],
        [0.3855, 0.4437, 0.5741],
        [0.0528, 0.3182, 0.0508]])


In [6]:
x = torch.tensor([1,2,3])
print(x)

y = torch.tensor([4,5,6])
print(y)

print(x+y)
print(x*y)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [7]:
x = torch.tensor([1.0, 2.0, 3.0])
w = torch.tensor(2.0, requires_grad=True)    #requires_grad=True このwについて勾配を追跡・計算できるようにする

y = w * x
loss = y.sum()

loss.backward()    #lossをwで微分　w.gradに計算結果（勾配）を保存

print(w.grad)    #gradは勾配を入れておく場所

tensor(6.)


In [12]:
w = torch.tensor(2.0, requires_grad=True)

x = torch.tensor([1.0, 2.0, 3.0])
target = torch.tensor([4.0, 8.0, 12.0])

optimizer = torch.optim.SGD([w], lr=0.02)    #optim.SGDはパラメータwの更新方法 Irは学習率　勾配をどれだけ使って重みを動かすか決める
#SGD = Stochastic Gradient Descent（確率的勾配降下法）

for i in range(10):
    y = w * x

    loss = ((y - target) ** 2).sum()

    optimizer.zero_grad()    #勾配を消す　これがないと勾配が蓄積していく
    loss.backward()    #新しい勾配を計算
    optimizer.step()    #wを更新　optimizerを実行

    print(i, "w =", w.item(), "loss =", loss.item())    #.itemは1要素だけ入っている値をPythonの数値として表示

0 w = 3.119999885559082 loss = 56.0
1 w = 3.612799882888794 loss = 10.841602325439453
2 w = 3.829631805419922 loss = 2.0989344120025635
3 w = 3.9250380992889404 loss = 0.40635451674461365
4 w = 3.9670166969299316 loss = 0.07867012172937393
5 w = 3.985487222671509 loss = 0.015230482444167137
6 w = 3.993614435195923 loss = 0.0029486692510545254
7 w = 3.997190237045288 loss = 0.0005708470125682652
8 w = 3.9987637996673584 loss = 0.00011053076741518453
9 w = 3.9994561672210693 loss = 2.139644493581727e-05


In [19]:
import torch.nn as nn

x = torch.tensor([[1.0, 2.0, 3.0]])
target = torch.tensor([[4.0, 8.0, 12.0]])

model = nn.Linear(in_features=3, out_features=3, bias=False)
# 3. 損失関数と最適化手法（オプティマイザ）の用意
criterion = nn.MSELoss()  # 平均二乗誤差（近づき具合を測る）
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)  # 確率的勾配降下法

# 4. 学習ループ（100回繰り返す）
for epoch in range(100):
    # 予測
    y = model(x)
    
    # 誤差の計算
    loss = ((y - target) ** 2).sum()
    
    # 勾配の計算と重みの更新
    optimizer.zero_grad()  # 勾配の初期化
    loss.backward()        # 逆伝播（勾配の計算）
    optimizer.step()       # 重みの更新
    
    # 20回ごとに進捗を表示
    if (epoch + 1) % 20 == 0:
        print("Epoch =", epoch+1, "w =", w.item(), "loss =", loss.item())

Epoch = 20 w = 3.9994561672210693 loss = 0.0007747462950646877
Epoch = 40 w = 3.9994561672210693 loss = 1.5643308870494366e-09
Epoch = 60 w = 3.9994561672210693 loss = 1.8758328224066645e-12
Epoch = 80 w = 3.9994561672210693 loss = 1.1937117960769683e-12
Epoch = 100 w = 3.9994561672210693 loss = 1.1937117960769683e-12
